apiVersion: v1
kind: Service
metadata:
  name: httpserver-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 3001
  selector:
    app: httpserver
